language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then travis_retry pip install pyopenssl ndg-httpsclient pyasn1
  - pip install pysnow requests httpretty
# command to run tests
script: nosetests tests/incident.py

